---
title: "Multiverse Meta-Analysis Exploring the Efficacy of Psychological Interventions for Depression"
subtitle: "5. Multiverse GOSH Plot"
author: "Constantin Yves Plessen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(metafor)
library(metaviz)
library(ggpubr)
library(grid)
library(gridExtra)
set.seed(42)
source("helper-functions/sca_gosh_rem.R")
library(readxl)
require(tictoc)
```

<br>

# Load and clean data

```{r}
data_rem <- read_csv("data/tidy/data_cleaned.csv")

data_avg <- data_rem %>% 
  escalc(yi=yi, vi=vi, data=.)

data_avg <- as.data.frame(aggregate(data_avg, cluster = study,                                      
                                    struct="CS" , #compound symmetric structure as nested are not indpendent
                                     rho = 0.5))

reml_avg <- rma(yi = data_avg$yi, vi = data_avg$vi, 
                method = "REML", 
                control = list(stepadj = 0.5,
                               maxiter = 2000))  
reml_avg
```

## Create GOSH Plot (parallelized)
```{r}
tic()
gosh_reml <- gosh(subsets = 100000, 
                  parallel = "snow",
                  ncpus = 9,
                  reml_avg)
toc()
```

## Inspect Plot
```{r}
gosh_plot <- plot(gosh_reml, breaks = 100)
gosh_plot
```

## Save Plot
```{r}
#pdf(file = "figures/gosh_dl.pdf",    # The directory you want to save the file in
#    width = 15, # The width of the plot in inches
#    height = 10) # The height of the plot in inches

plot(gosh_reml, breaks = 100)
#dev.off()
```
